// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmitR2tSIsnQYsWF0Sw9lmKNR8oRczpyc',
    appId: '1:253907087385:web:142c5061d47901d0a03a88',
    messagingSenderId: '253907087385',
    projectId: 'greentrash-xuanthao',
    authDomain: 'greentrash-xuanthao.firebaseapp.com',
    storageBucket: 'greentrash-xuanthao.firebasestorage.app',
    measurementId: 'G-KSCMFZ9DDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIiXUiZ1i5RYTwdbvNwy292D7Za4U2O00',
    appId: '1:253907087385:android:b249f34c203ee06ca03a88',
    messagingSenderId: '253907087385',
    projectId: 'greentrash-xuanthao',
    storageBucket: 'greentrash-xuanthao.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2x4LvIyu_HXcm71SuxUqxrPhZmn2lrUg',
    appId: '1:898442906799:ios:d5dab003049f0fcf0d185a',
    messagingSenderId: '898442906799',
    projectId: 'greentrashdb',
    storageBucket: 'greentrashdb.firebasestorage.app',
    iosBundleId: 'com.example.greenTrashProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2XiDEXY6w6grnVZKyLN84Dxzr9XcnAt0',
    appId: '1:898442906799:web:dd9294812f6845860d185a',
    messagingSenderId: '898442906799',
    projectId: 'greentrashdb',
    authDomain: 'greentrashdb.firebaseapp.com',
    storageBucket: 'greentrashdb.firebasestorage.app',
    measurementId: 'G-RHTBPYHRPV',
  );
}
